### ISSUE TITLE
Path()..moveTo() not working as intended with package?

### ISSUE THREAD

**Issue by 15tariqj** [leancodepl/dashed_line#1]
I'm trying to draw a dashed arc, however it appears that the Path()..moveTo() is not working as intended with the package.

```dart
Container(
  width: SizeConfig.safeScreenWidth!,
  height: SizeConfig.safeScreenHeight! * 4 / 9,
  child: DashedLine(
    path: Path()
      ..moveTo(
        SizeConfig.safeScreenWidth! * 0.2,
        (SizeConfig.safeScreenHeight! * 4 / 9) * 0.7,
      )
      ..quadraticBezierTo(
        SizeConfig.safeScreenWidth! * 0.5,
        (SizeConfig.safeScreenHeight! * 4 / 9) * 0.3,
        SizeConfig.safeScreenWidth! * 0.8,
        (SizeConfig.safeScreenHeight! * 4 / 9) * 0.7,
      ),
    dashSpace: 1,
    color: Colors.grey,
  )
)
```

This is the resulting curve:
<img width="431" alt="Screenshot 2021-04-09 at 18 33 45" src="https://user-images.githubusercontent.com/32335468/114219094-21551180-9962-11eb-9dd3-726db97338ea.png">

However, I'd like for the curve to start from 20% of the screen width, and end at 80% of the screen width, like this:
<img width="404" alt="Screenshot 2021-04-09 at 18 38 09" src="https://user-images.githubusercontent.com/32335468/114219579-beb04580-9962-11eb-9cea-8ca6b5ab5521.png">

which I achieved using the same path methods.

**Comment by Albert221** [comment]
`dashed_line` doesn't work like that.

What you are trying to achieve with your code is give absolute coordinates for the path to be constructed, but `dashed_line`  takes the smallest bounding box containing all of the control points as its _container_. What you may need to do to achieve your desired effect is to wrap `DashedLine` in a `Container` just like so:

```dart
Container(
  width: SizeConfig.safeScreenWidth! * 0.6,
  alignment: Alignment.center,
  child: DashedLine.svgPath(
    'M150 415 Q375 178 600 415',
    dashSpace: 1,
    color: Colors.grey,
  ),
)
```

This will make sure that the path is 60% of the width centered (so 20% space on each horizontal side).

![image](https://user-images.githubusercontent.com/4085280/114221332-7cd8cc80-996d-11eb-8d98-107552bba541.png)

**Comment by 15tariqj** [comment]
I see, thank you!
Out of curiosity, how did you generate that image, Figma?

**Comment by Albert221** [comment]
I constructed the SVG path by hand using your code and iPhone 8 resolution I found on Google in https://yqnn.github.io/svg-path-editor/ 😅
